import { useState, useEffect, useRef } from "react";

/* ═══ GLOBAL STYLES — manual dark mode toggle + mobile + hover ═══ */
const CSS = `
*{box-sizing:border-box;margin:0;padding:0}
:root{--bg:#FFFFFF;--bg2:#FFFFFF;--bg3:#F8FAFC;--tx:#0F172A;--tx2:#475569;--tx3:#94A3B8;--bd:#E2E8F0;--bd2:#CBD5E1;--teal:#0D9488;--navy:#1E3A5F;--coral:#EA580C;--pos:#059669;--neg:#DC2626;--warn:#D97706;--posbg:#D1FAE5;--negbg:#FEE2E2;--warnbg:#FEF3C7;--tealbg:#F0FDFA;--navybg:#EFF6FF;--pagebg:#F8FAFC}
.dark{--bg:#0B1120;--bg2:#151D2E;--bg3:#1C2840;--tx:#E8ECF2;--tx2:#8B9AB8;--tx3:#566380;--bd:#243045;--bd2:#2D3D55;--navybg:#1C2840;--tealbg:#12282A;--posbg:#12282A;--negbg:#2E1820;--warnbg:#2E2818;--pagebg:#0B1120}
body{font-family:system-ui,-apple-system,sans-serif;background:var(--pagebg);color:var(--tx)}
.card{background:var(--bg2);border:1px solid var(--bd);border-radius:12px;transition:box-shadow .2s,transform .2s}
.card:hover{box-shadow:0 4px 12px rgba(0,0,0,0.08)}
.card-click{cursor:pointer}.card-click:hover{transform:translateY(-2px);box-shadow:0 6px 20px rgba(0,0,0,0.1)}
.btn{border:none;border-radius:8px;font-weight:600;font-size:14px;cursor:pointer;transition:opacity .15s,transform .1s;font-family:inherit}
.btn:hover{opacity:0.9}.btn:active{transform:scale(0.98)}
.btn-coral{background:var(--coral);color:#fff;padding:10px 24px}
.btn-navy{background:var(--navy);color:#fff;padding:10px 20px}
.btn-teal{background:var(--teal);color:#fff;padding:10px 24px}
.btn-outline{background:var(--bg2);color:var(--tx2);border:1px solid var(--bd);padding:8px 16px}
.btn-outline:hover{background:var(--bg3)}
input,textarea,select{font-family:inherit;background:var(--bg2);color:var(--tx);border:1px solid var(--bd2);border-radius:8px;padding:10px 12px;font-size:14px;width:100%;outline:none;transition:border-color .15s}
input:focus,textarea:focus,select:focus{border-color:var(--teal)}
.badge{display:inline-block;font-size:11px;font-weight:600;padding:2px 8px;border-radius:99px}
.sidebar{width:256px;background:var(--bg2);border-right:1px solid var(--bd);display:flex;flex-direction:column;flex-shrink:0;overflow:hidden;transition:width .2s,transform .3s}
.sidebar.collapsed{width:64px}
.mobile-bar{display:none;position:sticky;top:0;z-index:100;padding:12px 16px;background:var(--bg2);border-bottom:1px solid var(--bd);align-items:center;justify-content:space-between}
.overlay{display:none;position:fixed;inset:0;background:rgba(0,0,0,0.4);z-index:200}
@media(max-width:768px){
  .sidebar{position:fixed;left:0;top:0;bottom:0;z-index:300;transform:translateX(-100%);width:256px!important}
  .sidebar.mobile-open{transform:translateX(0)}
  .sidebar.collapsed{width:256px!important}
  .mobile-bar{display:flex}
  .overlay.show{display:block}
  .main-content{padding:16px!important}
  .hide-mobile{display:none!important}
  .grid-2{grid-template-columns:1fr!important}
  .hero-wrap{flex-direction:column!important;padding:40px 16px 40px!important}
  .hero-wrap h1{font-size:32px!important}
  .hero-mockup{max-width:100%!important;transform:none!important}
  .nav-links{display:none!important}
  .show-mobile{display:flex!important}
  .landing-nav .btn-coral{padding:8px 14px!important;font-size:13px!important}
}
@media(max-width:480px){.stat-grid{grid-template-columns:1fr 1fr!important}}
`;

/* ═══ DATA ═══ */
const USER={name:"Sthe Mahlangu",email:"sthe@reviewpulse.com",plan:"Pro",used:127,limit:500};
const PROJECTS=[
  {id:"1",name:"ShopEase Google Reviews",desc:"E-commerce store reviews from Google Business",reviews:234,analyses:7,sentiment:61,last:"2 hours ago",industry:"E-commerce",p:45,nu:20,n:35},
  {id:"2",name:"TechFlow App Store",desc:"iOS and Android app store reviews",reviews:89,analyses:4,sentiment:72,last:"3 days ago",industry:"SaaS",p:58,nu:22,n:20},
  {id:"3",name:"CloudSync G2 Reviews",desc:"B2B software reviews from G2",reviews:45,analyses:2,sentiment:84,last:"1 week ago",industry:"SaaS",p:72,nu:16,n:12},
];
const REVIEWS=[
  {id:1,text:"Product quality is amazing but shipping took forever. Waited 3 weeks for a 5-day delivery.",rating:3,sent:"mixed",author:"Sarah M.",date:"Mar 28",src:"Google",tags:["Shipping","Quality"]},
  {id:2,text:"Absolutely love this! Customer support was incredibly helpful with my sizing question.",rating:5,sent:"positive",author:"James K.",date:"Mar 25",src:"Google",tags:["Support","Quality"]},
  {id:3,text:"Returned the item. Way too expensive for what you get. Materials feel cheap.",rating:1,sent:"negative",author:"Michelle T.",date:"Mar 22",src:"Trustpilot",tags:["Pricing","Quality"]},
  {id:4,text:"Great product, fast shipping! Packaging was nice. Wish they had more colors.",rating:4,sent:"positive",author:"David L.",date:"Mar 20",src:"Google",tags:["Shipping","Quality"]},
  {id:5,text:"Third order and quality has gone downhill. Stitching coming apart after two washes.",rating:2,sent:"negative",author:"Priya R.",date:"Mar 18",src:"Amazon",tags:["Quality"]},
  {id:6,text:"Decent for the price. Nothing spectacular but gets the job done.",rating:3,sent:"neutral",author:"Tom W.",date:"Mar 15",src:"Google",tags:["Pricing"]},
  {id:7,text:"New design is so much better! Impressed with improvements.",rating:5,sent:"positive",author:"Aisha B.",date:"Mar 12",src:"App Store",tags:["Quality"]},
  {id:8,text:"Wish the app had dark mode. Blinding at night. Otherwise solid.",rating:4,sent:"positive",author:"Carlos G.",date:"Mar 10",src:"App Store",tags:["Feature Request"]},
];
const ANA={
  summary:"Overall sentiment is moderately positive (61%), but shipping delays are a growing frustration. Customer support is a major strength — mentioned positively 3x more than industry average. Improving delivery communication could address 40% of negative reviews.",
  sent:{positive:45,neutral:20,negative:28,mixed:7},
  complaints:[
    {rank:1,title:"Slow Shipping / Delivery Delays",sev:"critical",freq:34,pct:28,trend:"growing",tip:"Add real-time tracking and proactive delay notifications"},
    {rank:2,title:"Declining Product Quality",sev:"high",freq:22,pct:18,trend:"growing",tip:"Audit manufacturing QA — complaints up 40% QoQ"},
    {rank:3,title:"Pricing Too High",sev:"medium",freq:15,pct:12,trend:"stable",tip:"Consider a mid-tier product line"},
    {rank:4,title:"Limited Color Options",sev:"low",freq:8,pct:7,trend:"stable",tip:"Survey customers on preferred colors"},
  ],
  praises:[{title:"Excellent Support",freq:38,pct:31,tip:"Highlight response times in ads"},{title:"Product Design",freq:28,pct:23,tip:"Use before/after in marketing"},{title:"Packaging Quality",freq:12,pct:10,tip:"Run unboxing campaign"}],
  features:[{title:"Dark Mode",demand:12,pct:10,urg:"high",tip:"High demand, low complexity"},{title:"More Colors",demand:8,pct:7,urg:"medium",tip:"Survey top 100 customers"},{title:"Order Tracking",demand:6,pct:5,urg:"high",tip:"Partner with shipping API"}],
  actions:[{pri:"P1",title:"Implement order tracking",why:"Addresses 28% of complaints. Fastest sentiment improvement.",effort:"Medium",impact:"+8-12 pts"},{pri:"P2",title:"Audit manufacturing QA",why:"Quality complaints up 40% QoQ.",effort:"High",impact:"-18% negatives"},{pri:"P3",title:"Add dark mode",why:"12 requests. Quick win.",effort:"Low",impact:"+0.2 stars"}],
  ratings:{5:42,4:28,3:35,2:18,1:11},count:234,date:"2 hours ago",
};
const TRENDS=[{m:"Oct",s:55,r:28,pos:38,neg:35,neu:27},{m:"Nov",s:58,r:34,pos:42,neg:30,neu:28},{m:"Dec",s:52,r:45,pos:36,neg:38,neu:26},{m:"Jan",s:59,r:38,pos:44,neg:28,neu:28},{m:"Feb",s:63,r:42,pos:48,neg:24,neu:28},{m:"Mar",s:61,r:47,pos:45,neg:28,neu:27}];
const INVOICES=[{d:"Mar 1, 2026",desc:"Pro Plan",amt:"$29.00"},{d:"Feb 1, 2026",desc:"Pro Plan",amt:"$29.00"},{d:"Jan 1, 2026",desc:"Pro Plan",amt:"$29.00"}];
const TESTIES=[{q:"Saved us 20 hours/month. Complaint ranking paid for itself.",n:"Rachel Kim",r:"E-commerce Mgr",c:"GreenLeaf"},{q:"Found a critical UX issue buried in 400 reviews.",n:"Marcus Chen",r:"Product Lead",c:"Flowstate"},{q:"Under $400/month and doesn't need a PhD to set up.",n:"Amara Osei",r:"Founder",c:"BiteBox"},{q:"Action items tell you exactly what to fix first.",n:"Liam O'Brien",r:"CX Director",c:"TravelNest"},{q:"We analyze competitor G2 reviews. Game-changer.",n:"Sofia Petrov",r:"Marketing Lead",c:"DataPulse"},{q:"Replaced $300/mo Birdeye. 10x better analysis.",n:"Jordan Hayes",r:"Agency Owner",c:"BrightStar"}];
const FAQS=[["What types of reviews can I analyze?","Any text-based customer reviews — Google, Amazon, Yelp, Trustpilot, G2, Capterra, App Store, Play Store, or any other source. Just paste the text or upload a CSV."],["How accurate is the AI analysis?","We use Claude (by Anthropic) which understands context, sarcasm, and nuance far better than basic NLP tools. It groups related complaints into themes rather than treating every keyword separately."],["Is my data secure?","Yes. Reviews are processed in real-time and not stored permanently unless you save them to a project. All data is encrypted in transit and at rest. We're GDPR compliant."],["Can I analyze reviews in other languages?","Yes. Our AI understands 50+ languages natively. No translation step needed — just paste reviews in any language."],["How is this different from Birdeye?","Birdeye costs $379+/month, requires weeks of onboarding, and locks you into annual contracts. ReviewPulse starts at $0, works in 30 seconds, and has no contracts. Our AI analysis is also more nuanced."],["Do I need to connect my review platforms?","No. You can start immediately by pasting text. Platform connections are optional for automatic syncing."],["Can I export results?","Yes. Pro and Business plans can export analysis results as PDF reports or CSV data files."],["What happens if I exceed my plan limit?","You'll see a prompt to upgrade. Your existing data and analyses are never deleted — you just can't add more reviews until the next billing cycle or you upgrade."]];

/* ═══ ICONS ═══ */
const I=({name,size=20,color="currentColor"})=>{
  const p={viewBox:"0 0 24 24",width:size,height:size,fill:"none",stroke:color,strokeWidth:"2",strokeLinecap:"round",strokeLinejoin:"round"};
  const m={
    logo:<svg viewBox="0 0 32 32" width={size} height={size}><rect x="4" y="18" width="5" height="10" rx="1.5" fill="#0D9488"/><rect x="13" y="10" width="5" height="18" rx="1.5" fill="#1E3A5F"/><rect x="22" y="14" width="5" height="14" rx="1.5" fill="#0D9488"/><path d="M2 16Q8 8 16 12Q24 6 30 10" stroke="#EA580C" strokeWidth="2.5" fill="none" strokeLinecap="round"/></svg>,
    dash:<svg {...p}><rect x="3" y="3" width="7" height="7" rx="1"/><rect x="14" y="3" width="7" height="4" rx="1"/><rect x="14" y="10" width="7" height="11" rx="1"/><rect x="3" y="13" width="7" height="8" rx="1"/></svg>,
    folder:<svg {...p}><path d="M22 19a2 2 0 01-2 2H4a2 2 0 01-2-2V5a2 2 0 012-2h5l2 3h9a2 2 0 012 2z"/></svg>,
    plus:<svg {...p}><line x1="12" y1="5" x2="12" y2="19"/><line x1="5" y1="12" x2="19" y2="12"/></svg>,
    trend:<svg {...p}><polyline points="23 6 13.5 15.5 8.5 10.5 1 18"/><polyline points="17 6 23 6 23 12"/></svg>,
    link:<svg {...p}><path d="M10 13a5 5 0 007.54.54l3-3a5 5 0 00-7.07-7.07l-1.72 1.71"/><path d="M14 11a5 5 0 00-7.54-.54l-3 3a5 5 0 007.07 7.07l1.71-1.71"/></svg>,
    gear:<svg {...p}><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 00.33 1.82l.06.06a2 2 0 010 2.83 2 2 0 01-2.83 0l-.06-.06a1.65 1.65 0 00-1.82-.33 1.65 1.65 0 00-1 1.51V21a2 2 0 01-4 0v-.09A1.65 1.65 0 009 19.4a1.65 1.65 0 00-1.82.33l-.06.06a2 2 0 01-2.83-2.83l.06-.06A1.65 1.65 0 004.68 15a1.65 1.65 0 00-1.51-1H3a2 2 0 010-4h.09A1.65 1.65 0 004.6 9a1.65 1.65 0 00-.33-1.82l-.06-.06a2 2 0 012.83-2.83l.06.06A1.65 1.65 0 009 4.68a1.65 1.65 0 001-1.51V3a2 2 0 014 0v.09a1.65 1.65 0 001 1.51 1.65 1.65 0 001.82-.33l.06-.06a2 2 0 012.83 2.83l-.06.06A1.65 1.65 0 0019.4 9a1.65 1.65 0 001.51 1H21a2 2 0 010 4h-.09a1.65 1.65 0 00-1.51 1z"/></svg>,
    card:<svg {...p}><rect x="1" y="4" width="22" height="16" rx="2"/><line x1="1" y1="10" x2="23" y2="10"/></svg>,
    cL:<svg {...p}><polyline points="15 18 9 12 15 6"/></svg>,cR:<svg {...p}><polyline points="9 18 15 12 9 6"/></svg>,cD:<svg {...p}><polyline points="6 9 12 15 18 9"/></svg>,cU:<svg {...p}><polyline points="18 15 12 9 6 15"/></svg>,
    ok:<svg {...p} strokeWidth="2.5"><polyline points="20 6 9 17 4 12"/></svg>,
    x:<svg {...p}><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>,
    clk:<svg {...p}><circle cx="12" cy="12" r="10"/><polyline points="12 6 12 12 16 14"/></svg>,
    $:<svg {...p}><line x1="12" y1="1" x2="12" y2="23"/><path d="M17 5H9.5a3.5 3.5 0 000 7h5a3.5 3.5 0 010 7H6"/></svg>,
    bar:<svg {...p}><line x1="12" y1="20" x2="12" y2="10"/><line x1="18" y1="20" x2="18" y2="4"/><line x1="6" y1="20" x2="6" y2="16"/></svg>,
    msg:<svg {...p}><path d="M21 15a2 2 0 01-2 2H7l-4 4V5a2 2 0 012-2h14a2 2 0 012 2z"/></svg>,
    srch:<svg {...p}><circle cx="11" cy="11" r="8"/><line x1="21" y1="21" x2="16.65" y2="16.65"/></svg>,
    bulb:<svg {...p}><path d="M9 18h6M10 22h4M12 2a7 7 0 014 12.73V17H8v-2.27A7 7 0 0112 2z"/></svg>,
    tgt:<svg {...p}><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="6"/><circle cx="12" cy="12" r="2"/></svg>,
    dl:<svg {...p}><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>,
    usr:<svg {...p}><path d="M20 21v-2a4 4 0 00-4-4H8a4 4 0 00-4 4v2"/><circle cx="12" cy="7" r="4"/></svg>,
    mail:<svg {...p}><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z"/><polyline points="22,6 12,13 2,6"/></svg>,
    lock:<svg {...p}><rect x="3" y="11" width="18" height="11" rx="2"/><path d="M7 11V7a5 5 0 0110 0v4"/></svg>,
    warn:<svg {...p}><path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z"/><line x1="12" y1="9" x2="12" y2="13"/><line x1="12" y1="17" x2="12.01" y2="17"/></svg>,
    play:<svg viewBox="0 0 24 24" width={size} height={size} fill={color} stroke="none"><polygon points="5 3 19 12 5 21"/></svg>,
    star:<svg viewBox="0 0 24 24" width={size} height={size} fill="#F59E0B" stroke="#F59E0B" strokeWidth="1"><polygon points="12 2 15.09 8.26 22 9.27 17 14.14 18.18 21.02 12 17.77 5.82 21.02 7 14.14 2 9.27 8.91 8.26"/></svg>,
    out:<svg {...p}><path d="M9 21H5a2 2 0 01-2-2V5a2 2 0 012-2h4"/><polyline points="16 17 21 12 16 7"/><line x1="21" y1="12" x2="9" y2="12"/></svg>,
    share:<svg {...p}><circle cx="18" cy="5" r="3"/><circle cx="6" cy="12" r="3"/><circle cx="18" cy="19" r="3"/><line x1="8.59" y1="13.51" x2="15.42" y2="17.49"/><line x1="15.41" y1="6.51" x2="8.59" y2="10.49"/></svg>,
    up:<svg {...p}><polyline points="16 16 12 12 8 16"/><line x1="12" y1="12" x2="12" y2="21"/><path d="M20.39 18.39A5 5 0 0018 9h-1.26A8 8 0 103 16.3"/></svg>,
    menu:<svg {...p}><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>,
    sun:<svg {...p}><circle cx="12" cy="12" r="5"/><line x1="12" y1="1" x2="12" y2="3"/><line x1="12" y1="21" x2="12" y2="23"/><line x1="4.22" y1="4.22" x2="5.64" y2="5.64"/><line x1="18.36" y1="18.36" x2="19.78" y2="19.78"/><line x1="1" y1="12" x2="3" y2="12"/><line x1="21" y1="12" x2="23" y2="12"/><line x1="4.22" y1="19.78" x2="5.64" y2="18.36"/><line x1="18.36" y1="5.64" x2="19.78" y2="4.22"/></svg>,
    moon:<svg {...p}><path d="M21 12.79A9 9 0 1111.21 3 7 7 0 0021 12.79z"/></svg>,
  };
  return m[name]||null;
};

/* ═══ TINY COMPONENTS ═══ */
const SB=({p,nu,n,h=8})=><div style={{display:"flex",borderRadius:99,overflow:"hidden",height:h,width:"100%"}}><div style={{width:`${p}%`,background:"var(--pos)"}}/><div style={{width:`${nu}%`,background:"var(--tx3)"}}/><div style={{width:`${n}%`,background:"var(--neg)"}}/></div>;
const Bg=({children,c="var(--teal)",bg="var(--tealbg)"})=><span className="badge" style={{background:bg,color:c}}>{children}</span>;
const St=({n=5})=><span style={{display:"inline-flex",gap:1}}>{Array.from({length:n},(_,i)=><I key={i} name="star" size={14}/>)}</span>;
const Dot=({v})=><span style={{width:10,height:10,borderRadius:"50%",background:v>=70?"var(--pos)":v>=50?"var(--warn)":"var(--neg)",display:"inline-block",marginRight:6}}/>;
const Donut=({data,sz=160})=>{const t=Object.values(data).reduce((a,b)=>a+b,0);const cs={positive:"#059669",neutral:"#94A3B8",negative:"#DC2626",mixed:"#D97706"};let cu=0;const sg=Object.entries(data).map(([k,v])=>{const s=cu;cu+=(v/t)*360;const r=60,sr=(s-90)*Math.PI/180,er=(cu-90)*Math.PI/180;return <path key={k} d={`M80,80 L${80+r*Math.cos(sr)},${80+r*Math.sin(sr)} A${r},${r} 0 ${v/t>.5?1:0},1 ${80+r*Math.cos(er)},${80+r*Math.sin(er)} Z`} fill={cs[k]}/>});return <svg viewBox="0 0 160 160" width={sz} height={sz}>{sg}<circle cx="80" cy="80" r="38" fill="var(--bg2)"/><text x="80" y="75" textAnchor="middle" fontSize="28" fontWeight="700" fill="var(--tx)">{Math.round((data.positive/t)*100)}</text><text x="80" y="93" textAnchor="middle" fontSize="10" fill="var(--tx2)">SCORE</text></svg>};
const Toast=({msg,type="success",onClose})=>{useEffect(()=>{const t=setTimeout(onClose,3000);return()=>clearTimeout(t)},[]);const s={success:{bg:"var(--posbg)",c:"var(--pos)"},error:{bg:"var(--negbg)",c:"var(--neg)"},info:{bg:"var(--navybg)",c:"var(--navy)"}}[type];return <div style={{position:"fixed",bottom:24,right:24,zIndex:9999,background:s.bg,color:s.c,borderRadius:10,padding:"12px 20px",fontSize:14,fontWeight:500,boxShadow:"0 8px 24px rgba(0,0,0,0.15)",display:"flex",alignItems:"center",gap:10,maxWidth:360}}>{msg}<span onClick={onClose} style={{cursor:"pointer",opacity:.5,marginLeft:8}}>×</span></div>};
const Modal=({title,children,onClose})=><div onClick={onClose} style={{position:"fixed",inset:0,zIndex:9000,background:"rgba(0,0,0,0.5)",backdropFilter:"blur(4px)",display:"flex",alignItems:"center",justifyContent:"center",padding:24}}><div onClick={e=>e.stopPropagation()} className="card" style={{padding:"28px 32px",width:"100%",maxWidth:480,boxShadow:"0 20px 60px rgba(0,0,0,0.2)",maxHeight:"90vh",overflow:"auto"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:20}}><h3 style={{fontSize:18,fontWeight:600}}>{title}</h3><span onClick={onClose} style={{cursor:"pointer",color:"var(--tx3)",fontSize:20}}>×</span></div>{children}</div></div>;
const SC={critical:{bg:"var(--negbg)",c:"var(--neg)"},high:{bg:"var(--warnbg)",c:"var(--coral)"},medium:{bg:"var(--warnbg)",c:"var(--warn)"},low:{bg:"var(--posbg)",c:"var(--pos)"}};
const PC={P1:{bg:"var(--negbg)",c:"var(--neg)"},P2:{bg:"var(--warnbg)",c:"var(--coral)"},P3:{bg:"var(--navybg)",c:"var(--navy)"}};
const Spin=()=><><div style={{width:48,height:48,border:"4px solid var(--bd)",borderTopColor:"var(--teal)",borderRadius:"50%",animation:"spin 1s linear infinite",margin:"0 auto 20px"}}/><style>{`@keyframes spin{to{transform:rotate(360deg)}}`}</style></>;

/* ═══ SHARED ANALYSIS RESULTS ═══ */
const AnalysisResults=({compact,nav,show})=>{const a=ANA;return <div>
  <div style={{background:"var(--tealbg)",borderLeft:"4px solid var(--teal)",borderRadius:12,padding:compact?20:24,marginBottom:16}}><div style={{fontWeight:600,fontSize:compact?14:15,color:"var(--teal)",marginBottom:6}}>Executive Summary</div><p style={{fontSize:14,lineHeight:1.7}}>{a.summary}</p></div>
  <div className="grid-2" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
    <div className="card" style={{padding:20}}><div style={{fontWeight:600,fontSize:14,marginBottom:12}}>Sentiment</div><div style={{display:"flex",alignItems:"center",gap:16}}><Donut data={a.sent} sz={compact?100:130}/><div style={{flex:1}}>{[["Positive",a.sent.positive,"var(--pos)"],["Neutral",a.sent.neutral,"var(--tx3)"],["Negative",a.sent.negative,"var(--neg)"],["Mixed",a.sent.mixed,"var(--warn)"]].map(([l,v,c])=><div key={l} style={{display:"flex",justifyContent:"space-between",marginBottom:5}}><div style={{display:"flex",alignItems:"center",gap:5}}><span style={{width:8,height:8,borderRadius:2,background:c}}/><span style={{fontSize:13,color:"var(--tx2)"}}>{l}</span></div><span style={{fontWeight:600,fontSize:13,color:c}}>{v}%</span></div>)}</div></div><div style={{marginTop:10}}><SB p={a.sent.positive} nu={a.sent.neutral} n={a.sent.negative} h={10}/></div></div>
    <div className="card" style={{padding:20}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:12}}><I name="warn" size={16} color="var(--neg)"/><span style={{fontWeight:600,fontSize:14}}>Top Issues</span></div>{a.complaints.slice(0,compact?3:4).map(c=><div key={c.rank} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 0",borderBottom:"1px solid var(--bd)"}}><span style={{fontSize:18,fontWeight:700,color:"var(--tx3)",width:24}}>#{c.rank}</span><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,marginBottom:2}}>{c.title}</div><div style={{fontSize:12,color:"var(--tx3)"}}>{c.freq} ({c.pct}%)</div></div><Bg c={SC[c.sev].c} bg={SC[c.sev].bg}>{c.sev}</Bg></div>)}</div>
  </div>
  <div className="grid-2" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16,marginBottom:16}}>
    <div className="card" style={{padding:20}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:12}}><span>💪</span><span style={{fontWeight:600,fontSize:14}}>Strengths</span></div>{a.praises.map((p,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderBottom:i<a.praises.length-1?"1px solid var(--bd)":"none"}}><div style={{width:8,height:8,borderRadius:"50%",background:"var(--pos)",flexShrink:0}}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:500}}>{p.title}</div><div style={{fontSize:12,color:"var(--tx3)"}}>{p.freq} ({p.pct}%)</div></div></div>)}</div>
    <div className="card" style={{padding:20}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:12}}><I name="bulb" size={16} color="var(--warn)"/><span style={{fontWeight:600,fontSize:14}}>Feature Requests</span></div>{a.features.map((f,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"8px 0",borderBottom:i<a.features.length-1?"1px solid var(--bd)":"none"}}><div style={{flex:1}}><div style={{fontSize:13,fontWeight:500}}>{f.title}</div><div style={{fontSize:12,color:"var(--tx3)"}}>{f.demand} requests</div></div><Bg c={f.urg==="high"?"var(--neg)":"var(--warn)"} bg={f.urg==="high"?"var(--negbg)":"var(--warnbg)"}>{f.urg}</Bg></div>)}</div>
  </div>
  <div className="card" style={{padding:20,marginBottom:16}}><div style={{display:"flex",alignItems:"center",gap:6,marginBottom:12}}><I name="tgt" size={16} color="var(--coral)"/><span style={{fontWeight:600,fontSize:14}}>Recommended Actions</span></div>{a.actions.map((it,i)=><div key={i} style={{display:"flex",alignItems:"flex-start",gap:10,padding:"10px 0",borderBottom:i<a.actions.length-1?"1px solid var(--bd)":"none"}}><Bg c={PC[it.pri].c} bg={PC[it.pri].bg}>{it.pri}</Bg><div style={{flex:1}}><div style={{fontSize:13,fontWeight:600,marginBottom:2}}>{it.title}</div><div style={{fontSize:12,color:"var(--tx2)"}}>{it.why}</div><div style={{display:"flex",gap:12,fontSize:11,color:"var(--tx3)",marginTop:4}}><span>Effort: <strong style={{color:"var(--tx2)"}}>{it.effort}</strong></span><span>Impact: <strong style={{color:"var(--pos)"}}>{it.impact}</strong></span></div></div></div>)}</div>
  {!compact&&<div className="card" style={{padding:24}}><div style={{fontWeight:600,fontSize:16,marginBottom:16}}>Rating Distribution</div>{[5,4,3,2,1].map(s=>{const c=a.ratings[s],t=Object.values(a.ratings).reduce((a,b)=>a+b,0);return <div key={s} style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><span style={{fontSize:13,width:24,textAlign:"right"}}>{s}★</span><div style={{flex:1,height:10,background:"var(--bd)",borderRadius:5}}><div style={{height:"100%",background:s>=4?"var(--pos)":s===3?"var(--warn)":"var(--neg)",borderRadius:5,width:`${(c/t)*100}%`}}/></div><span style={{fontSize:12,color:"var(--tx2)",width:28}}>{c}</span></div>})}</div>}
</div>};

/* ═══ LANDING ═══ */
const Landing=({nav,dark,tog})=>{
  const fr=useRef(null),pr=useRef(null),[faqOpen,setFaqOpen]=useState(null);
  const sc=r=>r.current?.scrollIntoView({behavior:"smooth"});
  return <div>
    <style>{CSS}</style>
    <nav className="landing-nav" style={{position:"sticky",top:0,zIndex:100,display:"flex",alignItems:"center",justifyContent:"space-between",padding:"12px 24px",backdropFilter:"blur(12px)",borderBottom:"1px solid var(--bd)",background:"var(--bg2)"}}>
      <div style={{display:"flex",alignItems:"center",gap:8,cursor:"pointer"}} onClick={()=>window.scrollTo({top:0,behavior:"smooth"})}><I name="logo" size={28}/><span style={{fontWeight:700,fontSize:18}}>ReviewPulse</span></div>
      <div className="nav-links" style={{display:"flex",gap:24,alignItems:"center",fontSize:14}}>
        <span style={{color:"var(--tx2)",cursor:"pointer"}} onClick={()=>sc(fr)}>Features</span>
        <span style={{color:"var(--tx2)",cursor:"pointer"}} onClick={()=>sc(pr)}>Pricing</span>
        <span onClick={tog} style={{cursor:"pointer",padding:4,borderRadius:6,display:"flex",alignItems:"center"}} title={dark?"Light mode":"Dark mode"}><I name={dark?"sun":"moon"} size={18} color="var(--tx2)"/></span>
        <span style={{color:"var(--navy)",cursor:"pointer",fontWeight:500}} onClick={()=>nav("login")}>Log In</span>
        <button className="btn btn-coral" onClick={()=>nav("signup")}>Get Started Free →</button>
      </div>
      <div style={{display:"none",gap:8,alignItems:"center"}} className="show-mobile">
        <span onClick={tog} style={{cursor:"pointer",padding:4,display:"flex"}}><I name={dark?"sun":"moon"} size={18} color="var(--tx2)"/></span>
        <button className="btn btn-coral" style={{padding:"8px 14px",fontSize:13}} onClick={()=>nav("signup")}>Get Started →</button>
      </div>
    </nav>
    {/* Hero */}
    <section className="hero-wrap" style={{display:"flex",alignItems:"center",justifyContent:"space-between",maxWidth:1200,margin:"0 auto",padding:"80px 24px 60px",gap:48,flexWrap:"wrap"}}>
      <div style={{flex:"1 1 480px",maxWidth:560}}>
        <h1 style={{fontSize:48,fontWeight:700,lineHeight:1.15,marginBottom:20}}>Turn Customer Reviews Into Your <span style={{color:"var(--teal)"}}>Unfair Advantage</span></h1>
        <p style={{fontSize:18,color:"var(--tx2)",lineHeight:1.6,marginBottom:28}}>Paste your reviews. Get AI-powered insights in seconds. Know exactly what customers love, hate, and wish you'd build.</p>
        <div style={{display:"flex",gap:12,marginBottom:16,flexWrap:"wrap"}}>
          <button className="btn btn-coral" style={{padding:"14px 28px",fontSize:16,boxShadow:"0 4px 14px rgba(234,88,12,0.3)"}} onClick={()=>nav("signup")}>Analyze Reviews Free →</button>
          <button className="btn btn-outline" style={{padding:"12px 24px",fontSize:16,display:"flex",alignItems:"center",gap:8}} onClick={()=>nav("signup")}><I name="play" size={14}/> Watch Demo</button>
        </div>
        <p style={{fontSize:13,color:"var(--tx3)"}}>No credit card required · Free forever plan · 10,000+ reviews analyzed</p>
      </div>
      <div className="hero-mockup card" style={{flex:"1 1 400px",maxWidth:520,padding:20,boxShadow:"0 20px 60px rgba(0,0,0,0.1)",transform:"rotate(1deg)"}}>
        <div style={{fontSize:13,fontWeight:600,marginBottom:12}}>Analysis — ShopEase</div>
        <div style={{display:"flex",gap:16,marginBottom:16}}><Donut data={ANA.sent} sz={100}/><div style={{flex:1}}>{[["Positive",45,"#059669"],["Neutral",20,"#94A3B8"],["Negative",28,"#DC2626"],["Mixed",7,"#D97706"]].map(([l,v,c])=><div key={l} style={{display:"flex",alignItems:"center",gap:6,marginBottom:6,fontSize:12}}><span style={{width:8,height:8,borderRadius:2,background:c}}/><span style={{color:"var(--tx2)"}}>{l}</span><span style={{marginLeft:"auto",fontWeight:600}}>{v}%</span></div>)}</div></div>
        <div style={{background:"var(--negbg)",borderRadius:8,padding:"8px 12px",fontSize:12,color:"var(--neg)",marginBottom:8}}><strong>#1:</strong> Slow shipping — 28% ↑</div>
        <div style={{background:"var(--posbg)",borderRadius:8,padding:"8px 12px",fontSize:12,color:"var(--pos)"}}><strong>Strength:</strong> Customer support — 31%</div>
      </div>
    </section>
    <section style={{borderTop:"1px solid var(--bd)",borderBottom:"1px solid var(--bd)",padding:"20px 24px",textAlign:"center"}}><p style={{fontSize:13,color:"var(--tx3)",letterSpacing:"0.05em",textTransform:"uppercase",fontWeight:500}}>Works with: Google · Amazon · Yelp · Trustpilot · G2 · Capterra · App Store · Play Store</p></section>
    {/* Problem */}
    <section style={{maxWidth:1000,margin:"0 auto",padding:"64px 24px",textAlign:"center"}}>
      <h2 style={{fontSize:32,fontWeight:700,marginBottom:40}}>You're Sitting on a <span style={{color:"var(--teal)"}}>Goldmine</span></h2>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(250px,1fr))",gap:20,marginBottom:32}}>{[["$","Hours Wasted","Reading hundreds of reviews manually","var(--negbg)","var(--neg)"],["srch","Blind Spots","Critical complaints buried in 5-star reviews","var(--warnbg)","var(--warn)"],["trend","Revenue Lost","Competitors fix issues you don't know about","var(--negbg)","var(--neg)"]].map(([ic,t,d,bg,c])=><div key={t} className="card" style={{padding:28,textAlign:"center"}}><div style={{width:44,height:44,borderRadius:10,background:bg,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px"}}><I name={ic} color={c} size={22}/></div><div style={{fontWeight:600,fontSize:16,marginBottom:8}}>{t}</div><div style={{fontSize:14,color:"var(--tx2)",lineHeight:1.5}}>{d}</div></div>)}</div>
      <p style={{fontSize:18,color:"var(--teal)",fontWeight:600}}>ReviewPulse finds every pattern and tells you what to fix — in 30 seconds.</p>
    </section>
    {/* Steps */}
    <section ref={fr} style={{background:"var(--bg3)",padding:"64px 24px"}}><div style={{maxWidth:900,margin:"0 auto",textAlign:"center"}}><h2 style={{fontSize:32,fontWeight:700,marginBottom:48}}>Three Steps to Clarity</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))",gap:32}}>{[["msg","1. Paste or Upload","Drop reviews in. Paste, CSV, or connect.","var(--navybg)","var(--navy)"],["bulb","2. AI Analyzes","Reads every review, detects sarcasm, groups by theme.","var(--tealbg)","var(--teal)"],["bar","3. Get Insights","What customers love, hate, and what to fix first.","var(--warnbg)","var(--coral)"]].map(([ic,t,d,bg,c])=><div key={t}><div style={{width:56,height:56,borderRadius:14,background:bg,display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 16px"}}><I name={ic} color={c} size={26}/></div><div style={{fontWeight:600,fontSize:16,marginBottom:8}}>{t}</div><div style={{fontSize:14,color:"var(--tx2)",lineHeight:1.5}}>{d}</div></div>)}</div></div></section>
    {/* Pricing */}
    <section ref={pr} style={{maxWidth:1000,margin:"0 auto",padding:"64px 24px",textAlign:"center"}}>
      <h2 style={{fontSize:32,fontWeight:700,marginBottom:8}}>Simple, Honest Pricing</h2>
      <p style={{fontSize:16,color:"var(--tx2)",marginBottom:40}}>No annual contracts. No hidden fees.</p>
      <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(260px,1fr))",gap:20,alignItems:"start"}}>
        {[{n:"Free",p:"$0",f:["50 reviews/month","1 project","Basic sentiment"],cta:"Start Free",cls:"btn-navy",hl:false},{n:"Pro",p:"$29",f:["500 reviews/month","10 projects","Full AI analysis","Trend tracking","Export reports"],cta:"Start Free Trial",cls:"btn-coral",hl:true},{n:"Business",p:"$79",f:["Unlimited everything","API access","Team (5)","Slack + webhooks"],cta:"Start Free Trial",cls:"btn-navy",hl:false}].map(pl=><div key={pl.n} className="card" style={{padding:32,border:pl.hl?"2px solid var(--teal)":"",transform:pl.hl?"scale(1.03)":"",boxShadow:pl.hl?"0 8px 30px rgba(13,148,136,0.15)":"",position:"relative"}}>{pl.hl&&<div style={{position:"absolute",top:-12,left:"50%",transform:"translateX(-50%)",background:"var(--teal)",color:"#fff",fontSize:11,fontWeight:700,padding:"4px 14px",borderRadius:99,textTransform:"uppercase"}}>Most Popular</div>}<div style={{fontSize:16,fontWeight:600,marginBottom:4}}>{pl.n}</div><div style={{fontSize:40,fontWeight:700,marginBottom:4}}>{pl.p}<span style={{fontSize:16,fontWeight:400,color:"var(--tx2)"}}>/mo</span></div><div style={{borderTop:"1px solid var(--bd)",margin:"16px 0",paddingTop:16}}>{pl.f.map(f=><div key={f} style={{display:"flex",alignItems:"center",gap:8,fontSize:14,color:"var(--tx2)",marginBottom:10}}><I name="ok" size={16} color="var(--pos)"/>{f}</div>)}</div><button className={`btn ${pl.cls}`} style={{width:"100%"}} onClick={()=>nav("signup")}>{pl.cta}</button></div>)}</div>
    </section>
    {/* Testimonials */}
    <section style={{background:"var(--bg3)",padding:"64px 24px"}}><div style={{maxWidth:1100,margin:"0 auto"}}><h2 style={{fontSize:32,fontWeight:700,textAlign:"center",marginBottom:40}}>Loved by Teams & Founders</h2><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(300px,1fr))",gap:20}}>{TESTIES.map((t,i)=><div key={i} className="card" style={{padding:24}}><St/><p style={{fontSize:14,color:"var(--tx2)",lineHeight:1.6,margin:"12px 0 16px",fontStyle:"italic"}}>"{t.q}"</p><div style={{display:"flex",alignItems:"center",gap:10}}><div style={{width:36,height:36,borderRadius:"50%",background:"var(--navybg)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:13,fontWeight:600,color:"var(--navy)"}}>{t.n.split(" ").map(x=>x[0]).join("")}</div><div><div style={{fontWeight:600,fontSize:13}}>{t.n}</div><div style={{fontSize:12,color:"var(--tx3)"}}>{t.r}, {t.c}</div></div></div></div>)}</div></div></section>
    {/* FAQ */}
    <section style={{maxWidth:800,margin:"0 auto",padding:"64px 24px"}}>
      <h2 style={{fontSize:32,fontWeight:700,textAlign:"center",marginBottom:40}}>Frequently Asked Questions</h2>
      {FAQS.map(([q,a],i)=><div key={i} className="card" style={{marginBottom:8,overflow:"hidden"}}>
        <div onClick={()=>setFaqOpen(faqOpen===i?null:i)} style={{padding:"16px 20px",display:"flex",justifyContent:"space-between",alignItems:"center",cursor:"pointer"}}><span style={{fontWeight:600,fontSize:15}}>{q}</span><I name={faqOpen===i?"cU":"cD"} size={18} color="var(--tx3)"/></div>
        {faqOpen===i&&<div style={{padding:"0 20px 16px",fontSize:14,color:"var(--tx2)",lineHeight:1.6}}>{a}</div>}
      </div>)}
    </section>
    {/* CTA */}
    <section style={{background:"linear-gradient(135deg,#0F172A,#1E3A5F)",padding:"64px 24px",textAlign:"center"}}><h2 style={{fontSize:36,fontWeight:700,color:"#fff",marginBottom:12}}>Stop Guessing. Start Understanding.</h2><p style={{fontSize:16,color:"rgba(255,255,255,0.7)",marginBottom:28}}>Join 2,000+ businesses turning feedback into growth.</p><button className="btn btn-coral" style={{padding:"14px 32px",fontSize:16,boxShadow:"0 4px 20px rgba(234,88,12,0.4)"}} onClick={()=>nav("signup")}>Get Started Free →</button><p style={{fontSize:13,color:"rgba(255,255,255,0.5)",marginTop:12}}>No credit card required</p></section>
    <footer style={{borderTop:"1px solid var(--bd)",padding:"40px 24px",maxWidth:1200,margin:"0 auto"}}><div style={{display:"flex",justifyContent:"space-between",flexWrap:"wrap",gap:32}}><div><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:8}}><I name="logo" size={24}/><span style={{fontWeight:700}}>ReviewPulse</span></div><p style={{fontSize:13,color:"var(--tx3)"}}>AI-powered review insights</p></div>{[["Product",[["Features",()=>sc(fr)],["Pricing",()=>sc(pr)]]],["Company",[["About",()=>{}],["Blog",()=>{}]]],["Legal",[["Privacy",()=>{}],["Terms",()=>{}]]]].map(([t,ls])=><div key={t}><div style={{fontWeight:600,fontSize:13,marginBottom:12}}>{t}</div>{ls.map(([l,fn])=><div key={l} onClick={fn} style={{fontSize:13,color:"var(--tx3)",marginBottom:8,cursor:"pointer"}}>{l}</div>)}</div>)}</div><div style={{borderTop:"1px solid var(--bd)",marginTop:32,paddingTop:16,fontSize:12,color:"var(--tx3)"}}>© 2026 ReviewPulse. All rights reserved.</div></footer>
  </div>;
};

/* ═══ AUTH ═══ */
const Auth=({type,nav})=>{
  const [sent,setSent]=useState(false);
  if(type==="forgot"&&sent) return <div style={{minHeight:"100vh",background:"var(--bg)",display:"flex",alignItems:"center",justifyContent:"center",padding:24}}><style>{CSS}</style><div className="card" style={{padding:"48px 36px",width:"100%",maxWidth:420,textAlign:"center"}}><div style={{width:56,height:56,borderRadius:"50%",background:"var(--posbg)",display:"flex",alignItems:"center",justifyContent:"center",margin:"0 auto 20px"}}><I name="ok" size={28} color="var(--pos)"/></div><h2 style={{fontSize:22,fontWeight:700,marginBottom:8}}>Check your email</h2><p style={{fontSize:14,color:"var(--tx2)",marginBottom:24}}>We've sent a password reset link.</p><button className="btn btn-navy" onClick={()=>nav("login")}>Back to Login</button></div></div>;
  return <div style={{minHeight:"100vh",background:"var(--bg)",display:"flex",alignItems:"center",justifyContent:"center",padding:24}}><style>{CSS}</style><div className="card" style={{padding:"40px 36px",width:"100%",maxWidth:420}}>
    <div style={{display:"flex",alignItems:"center",gap:8,justifyContent:"center",marginBottom:28,cursor:"pointer"}} onClick={()=>nav("landing")}><I name="logo" size={28}/><span style={{fontWeight:700,fontSize:18}}>ReviewPulse</span></div>
    <h2 style={{fontSize:22,fontWeight:700,textAlign:"center",marginBottom:4}}>{type==="signup"?"Create your free account":type==="login"?"Welcome back":"Reset your password"}</h2>
    <p style={{fontSize:14,color:"var(--tx2)",textAlign:"center",marginBottom:24}}>{type==="signup"?"No credit card required.":type==="login"?"Log in to your account":"We'll send a reset link"}</p>
    {type==="signup"&&<div style={{marginBottom:16}}><label style={{fontSize:13,fontWeight:500,color:"var(--tx2)",display:"block",marginBottom:4}}>Full name</label><div style={{display:"flex",alignItems:"center",border:"1px solid var(--bd2)",borderRadius:8,padding:"0 12px",background:"var(--bg2)"}}><I name="usr" size={16} color="var(--tx3)"/><input placeholder="Sthe Mahlangu" style={{border:"none",padding:"10px 8px",flex:1}}/></div></div>}
    <div style={{marginBottom:16}}><label style={{fontSize:13,fontWeight:500,color:"var(--tx2)",display:"block",marginBottom:4}}>Email</label><div style={{display:"flex",alignItems:"center",border:"1px solid var(--bd2)",borderRadius:8,padding:"0 12px",background:"var(--bg2)"}}><I name="mail" size={16} color="var(--tx3)"/><input type="email" placeholder="you@company.com" style={{border:"none",padding:"10px 8px",flex:1}}/></div></div>
    {type!=="forgot"&&<div style={{marginBottom:20}}><label style={{fontSize:13,fontWeight:500,color:"var(--tx2)",display:"block",marginBottom:4}}>Password</label><div style={{display:"flex",alignItems:"center",border:"1px solid var(--bd2)",borderRadius:8,padding:"0 12px",background:"var(--bg2)"}}><I name="lock" size={16} color="var(--tx3)"/><input type="password" placeholder="••••••••" style={{border:"none",padding:"10px 8px",flex:1}}/></div>{type==="signup"&&<div style={{height:4,borderRadius:2,background:"var(--bd)",marginTop:8}}><div style={{height:"100%",borderRadius:2,background:"var(--warn)",width:"60%"}}/></div>}</div>}
    {type==="login"&&<div style={{display:"flex",justifyContent:"space-between",marginBottom:20,fontSize:13}}><label style={{display:"flex",alignItems:"center",gap:6,color:"var(--tx2)",cursor:"pointer"}}><input type="checkbox"/> Remember me</label><span style={{color:"var(--navy)",cursor:"pointer",fontWeight:500}} onClick={()=>nav("forgot")}>Forgot password?</span></div>}
    <button className="btn btn-navy" style={{width:"100%",marginBottom:16}} onClick={()=>type==="forgot"?setSent(true):nav("dashboard")}>{type==="signup"?"Create Account":type==="login"?"Log In":"Send Reset Link"}</button>
    {type!=="forgot"&&<><div style={{textAlign:"center",fontSize:13,color:"var(--tx3)",margin:"16px 0"}}>or continue with</div><button className="btn btn-outline" style={{width:"100%"}} onClick={()=>nav("dashboard")}>Google</button></>}
    <p style={{textAlign:"center",fontSize:13,color:"var(--tx2)",marginTop:20}}>{type==="signup"?<span>Have an account? <span style={{color:"var(--navy)",cursor:"pointer",fontWeight:600}} onClick={()=>nav("login")}>Log in</span></span>:type==="login"?<span>No account? <span style={{color:"var(--navy)",cursor:"pointer",fontWeight:600}} onClick={()=>nav("signup")}>Sign up free</span></span>:<span style={{color:"var(--navy)",cursor:"pointer"}} onClick={()=>nav("login")}>← Back to login</span>}</p>
  </div></div>;
};

/* ═══ DASHBOARD SHELL ═══ */
const Shell=({page,nav,dark,tog})=>{
  const [col,setCol]=useState(false);const [um,setUm]=useState(false);const [mob,setMob]=useState(false);
  const [toast,setToast]=useState(null);const show=(m,t="success")=>setToast({m,t});
  const items=[{id:"dashboard",ic:"dash",l:"Dashboard"},{id:"projects",ic:"folder",l:"Projects"},{id:"analysis",ic:"plus",l:"New Analysis",acc:true},{id:"trends",ic:"trend",l:"Trends"},{id:"integrations",ic:"link",l:"Integrations"},{id:"settings",ic:"gear",l:"Settings"},{id:"billing",ic:"card",l:"Billing"}];
  const act=id=>page===id||(page==="project"&&id==="projects");
  const go=id=>{nav(id);setUm(false);setMob(false)};
  return <div style={{display:"flex",minHeight:"100vh",background:"var(--pagebg)"}}><style>{CSS}</style>
    {/* Mobile overlay */}
    <div className={`overlay ${mob?"show":""}`} onClick={()=>setMob(false)}/>
    {/* Mobile top bar */}
    <div className="mobile-bar"><button className="btn btn-outline" style={{padding:6}} onClick={()=>setMob(!mob)}><I name="menu" size={20}/></button><div style={{display:"flex",alignItems:"center",gap:6}}><I name="logo" size={24}/><span style={{fontWeight:700}}>ReviewPulse</span></div><div onClick={()=>setUm(!um)} style={{width:32,height:32,borderRadius:"50%",background:"var(--navybg)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:600,color:"var(--navy)",cursor:"pointer"}}>SM</div></div>
    {/* Sidebar */}
    <aside className={`sidebar ${col?"collapsed":""} ${mob?"mobile-open":""}`}>
      <div onClick={()=>go("dashboard")} style={{padding:"16px 12px",display:"flex",alignItems:"center",gap:8,borderBottom:"1px solid var(--bd)",cursor:"pointer",justifyContent:col?"center":"flex-start"}}><I name="logo" size={28}/>{!col&&<span style={{fontWeight:700,fontSize:16,whiteSpace:"nowrap"}}>ReviewPulse</span>}</div>
      <nav style={{flex:1,padding:8}}>{items.map(it=><div key={it.id} onClick={()=>go(it.id)} style={{display:"flex",alignItems:"center",gap:10,padding:col?"10px 0":"10px 12px",borderRadius:8,marginBottom:2,cursor:"pointer",justifyContent:col?"center":"flex-start",background:it.acc?"var(--teal)":act(it.id)?"var(--navybg)":"transparent",color:it.acc?"#fff":act(it.id)?"var(--navy)":"var(--tx2)",fontWeight:act(it.id)||it.acc?600:400,fontSize:14,borderLeft:act(it.id)&&!it.acc?"3px solid var(--teal)":"3px solid transparent"}}><I name={it.ic} size={18} color={it.acc?"#fff":act(it.id)?"var(--navy)":"var(--tx2)"}/>{!col&&<span style={{whiteSpace:"nowrap"}}>{it.l}</span>}</div>)}</nav>
      <div style={{borderTop:"1px solid var(--bd)",padding:col?"12px 8px":"16px 12px"}}>
        {!col&&<div style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:12,color:"var(--tx2)",marginBottom:6}}><span>Reviews</span><span style={{fontWeight:600}}>{USER.used}/{USER.limit}</span></div><div style={{height:6,background:"var(--bd)",borderRadius:3}}><div style={{height:"100%",background:"var(--teal)",borderRadius:3,width:`${(USER.used/USER.limit)*100}%`}}/></div><div style={{fontSize:11,color:"var(--tx3)",marginTop:4}}>{USER.plan} plan</div></div>}
        <div style={{position:"relative"}}>
          <div onClick={()=>setUm(!um)} style={{display:"flex",alignItems:"center",gap:8,cursor:"pointer",justifyContent:col?"center":"flex-start"}}><div style={{width:32,height:32,borderRadius:"50%",background:"var(--navybg)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:12,fontWeight:600,color:"var(--navy)",flexShrink:0}}>SM</div>{!col&&<div style={{overflow:"hidden",flex:1}}><div style={{fontSize:13,fontWeight:600,whiteSpace:"nowrap"}}>{USER.name}</div><div style={{fontSize:11,color:"var(--tx3)",whiteSpace:"nowrap",overflow:"hidden",textOverflow:"ellipsis"}}>{USER.email}</div></div>}{!col&&<I name="cD" size={14} color="var(--tx3)"/>}</div>
          {um&&<div className="card" style={{position:"absolute",bottom:"100%",left:0,right:col?"auto":0,width:col?200:"auto",marginBottom:4,zIndex:50,borderRadius:10,boxShadow:"0 8px 24px rgba(0,0,0,0.15)",overflow:"hidden"}}>
            {[["Profile",()=>go("settings")],["Billing",()=>go("billing")],["Help",()=>{show("Help center coming soon!","info");setUm(false)}]].map(([l,fn])=><div key={l} onClick={fn} style={{padding:"10px 16px",fontSize:13,color:"var(--tx2)",cursor:"pointer",borderBottom:"1px solid var(--bd)"}}>{l}</div>)}
            <div onClick={()=>go("landing")} style={{padding:"10px 16px",fontSize:13,color:"var(--neg)",cursor:"pointer",display:"flex",alignItems:"center",gap:8}}><I name="out" size={14} color="var(--neg)"/>Sign Out</div>
          </div>}
        </div>
      </div>
      <div onClick={tog} style={{padding:col?"8px 0":"8px 12px",display:"flex",alignItems:"center",gap:8,borderTop:"1px solid var(--bd)",cursor:"pointer",color:"var(--tx2)",fontSize:13,justifyContent:col?"center":"flex-start"}}><I name={dark?"sun":"moon"} size={16} color="var(--tx2)"/>{!col&&<span>{dark?"Light mode":"Dark mode"}</span>}</div>
      <div className="hide-mobile" onClick={()=>setCol(!col)} style={{padding:8,textAlign:"center",borderTop:"1px solid var(--bd)",cursor:"pointer",color:"var(--tx3)"}}><I name={col?"cR":"cL"} size={16}/></div>
    </aside>
    <main className="main-content" style={{flex:1,padding:"24px 32px",overflow:"auto",maxWidth:1200}}>
      {page==="dashboard"&&<DashHome nav={nav} show={show}/>}
      {page==="projects"&&<ProjList nav={nav} show={show}/>}
      {page==="project"&&<ProjDet nav={nav} show={show}/>}
      {page==="analysis"&&<ProjDet nav={nav} show={show} st="add"/>}
      {page==="trends"&&<TrendsP/>}
      {page==="integrations"&&<IntegP show={show}/>}
      {page==="settings"&&<SetP nav={nav} show={show}/>}
      {page==="billing"&&<BillP nav={nav} show={show}/>}
    </main>
    {toast&&<Toast msg={toast.m} type={toast.t} onClose={()=>setToast(null)}/>}
  </div>;
};

/* ═══ DASHBOARD HOME ═══ */
const DashHome=({nav,show})=>{const [paste,setPaste]=useState("");const [busy,setBusy]=useState(false);const [done,setDone]=useState(false);const [prog,setProg]=useState(0);const [pmsg,setPmsg]=useState("");
  const steps=[[10,"Reading reviews..."],[25,"Detecting sentiment..."],[45,"Finding patterns..."],[60,"Extracting requests..."],[75,"Ranking severity..."],[90,"Generating actions..."],[100,"Finalizing..."]];
  const run=()=>{setBusy(true);setDone(false);steps.forEach(([p,m],i)=>setTimeout(()=>{setProg(p);setPmsg(m)},i*450));setTimeout(()=>{setBusy(false);setDone(true);show("Analysis complete!")},steps.length*450+200)};
  return <div><h1 style={{fontSize:24,fontWeight:600,marginBottom:4}}>Good morning, Sthe</h1><p style={{fontSize:14,color:"var(--tx2)",marginBottom:24}}>Pro plan · {USER.used} of {USER.limit} reviews used</p>
    <div className="stat-grid" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:24}}>{[["Reviews","368","↑ 12%"],["Projects","3",""],["Analyses","13",""],["Sentiment","72",""]].map(([l,v,t])=><div key={l} className="card" style={{padding:"16px 20px"}}><div style={{fontSize:12,color:"var(--tx2)",textTransform:"uppercase",letterSpacing:"0.05em",fontWeight:500,marginBottom:4}}>{l}</div><div style={{fontSize:28,fontWeight:600,color:l==="Sentiment"?"var(--pos)":"var(--tx)"}}>{v}</div>{t&&<div style={{fontSize:12,color:"var(--pos)",marginTop:4}}>{t}</div>}</div>)}</div>
    {!done&&!busy&&<div className="card" style={{padding:24,marginBottom:24}}><div style={{fontWeight:600,fontSize:16,marginBottom:12}}>Quick Analysis</div><textarea value={paste} onChange={e=>setPaste(e.target.value)} rows={5} placeholder={"Paste reviews here for instant insights...\n\nThe product quality is amazing but shipping took forever.\n\nLove the new features! Support was super helpful."}  style={{resize:"vertical",lineHeight:1.6}}/><div style={{display:"flex",gap:8,marginTop:12,alignItems:"center"}}><button className="btn btn-teal" onClick={()=>{if(!paste.trim()){show("Paste reviews first","error");return}run()}}>Analyze →</button><button className="btn btn-outline" onClick={()=>nav("analysis")}>Upload CSV</button>{paste.trim()&&<span style={{fontSize:13,color:"var(--tx3)",marginLeft:8}}>{paste.split(/\n\n+/).filter(Boolean).length} detected</span>}</div></div>}
    {busy&&<div className="card" style={{padding:"40px 24px",marginBottom:24,textAlign:"center"}}><Spin/><div style={{fontWeight:600,fontSize:16,marginBottom:8}}>Analyzing {paste.split(/\n\n+/).filter(Boolean).length} reviews...</div><div style={{fontSize:14,color:"var(--tx2)",marginBottom:16}}>{pmsg}</div><div style={{maxWidth:400,margin:"0 auto"}}><div style={{height:8,background:"var(--bd)",borderRadius:4}}><div style={{height:"100%",background:"linear-gradient(90deg,var(--teal),var(--pos))",borderRadius:4,width:`${prog}%`,transition:"width 0.4s"}}/></div><div style={{fontSize:12,color:"var(--tx3)",marginTop:6}}>{prog}%</div></div></div>}
    {done&&<div style={{marginBottom:24}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16,flexWrap:"wrap",gap:8}}><div><div style={{fontWeight:600,fontSize:18}}>Analysis Results</div><div style={{fontSize:13,color:"var(--tx3)"}}>{paste.split(/\n\n+/).filter(Boolean).length} reviews · Just now</div></div><div style={{display:"flex",gap:8}}><button className="btn btn-outline" onClick={()=>{setDone(false);setPaste("")}}>New Analysis</button><button className="btn btn-navy" onClick={()=>nav("project")}>Open Full Report →</button></div></div><AnalysisResults compact nav={nav} show={show}/></div>}
    <div style={{fontWeight:600,fontSize:16,marginBottom:12}}>Recent Projects</div>
    <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(300px,1fr))",gap:12,marginBottom:24}}>{PROJECTS.map(p=><div key={p.id} className="card card-click" style={{padding:20}} onClick={()=>nav("project")}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><span style={{fontWeight:600,fontSize:15}}>{p.name}</span><Dot v={p.sentiment}/></div><div style={{fontSize:13,color:"var(--tx2)",marginBottom:12}}>{p.reviews} reviews · {p.last}</div><SB p={p.p} nu={p.nu} n={p.n}/></div>)}</div>
    <div style={{fontWeight:600,fontSize:16,marginBottom:12}}>Recent Insights</div>
    {[{ic:"warn",c:"var(--neg)",bg:"var(--negbg)",t:"Critical: 'Shipping delays' in 34% of negatives",pr:"ShopEase",ti:"2h ago"},{ic:"trend",c:"var(--pos)",bg:"var(--posbg)",t:"Positive: Support praise up 15%",pr:"TechFlow",ti:"Yesterday"},{ic:"bulb",c:"var(--warn)",bg:"var(--warnbg)",t:"Feature request: Dark mode — 12 asks",pr:"CloudSync",ti:"2d ago"}].map((it,i)=><div key={i} className="card card-click" style={{padding:"12px 16px",marginBottom:8,display:"flex",gap:12,alignItems:"center"}} onClick={()=>nav("project")}><div style={{width:32,height:32,borderRadius:8,background:it.bg,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><I name={it.ic} size={16} color={it.c}/></div><div style={{flex:1}}><div style={{fontSize:14,fontWeight:500}}>{it.t}</div><div style={{fontSize:12,color:"var(--tx3)"}}>{it.pr} · {it.ti}</div></div></div>)}
  </div>;
};

/* ═══ PROJECTS ═══ */
const ProjList=({nav,show})=>{const [mo,setMo]=useState(false);const [nm,setNm]=useState("");return <div>
  <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24}}><h1 style={{fontSize:24,fontWeight:600}}>Projects</h1><button className="btn btn-navy" style={{display:"flex",alignItems:"center",gap:6}} onClick={()=>setMo(true)}><I name="plus" size={16} color="#fff"/> New Project</button></div>
  <div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(320px,1fr))",gap:16}}>{PROJECTS.map(p=><div key={p.id} className="card card-click" style={{padding:24}} onClick={()=>nav("project")}><div style={{fontWeight:600,fontSize:16,marginBottom:4}}>{p.name}</div><div style={{fontSize:13,color:"var(--tx2)",marginBottom:12}}>{p.desc}</div><div style={{fontSize:12,color:"var(--tx3)",marginBottom:12}}>{p.reviews} reviews · {p.analyses} analyses · {p.last}</div><SB p={p.p} nu={p.nu} n={p.n}/><div style={{display:"flex",gap:8,marginTop:12}}><Bg>{p.industry}</Bg><Bg c={p.sentiment>=70?"var(--pos)":"var(--warn)"} bg={p.sentiment>=70?"var(--posbg)":"var(--warnbg)"}>Score: {p.sentiment}</Bg></div></div>)}</div>
  {mo&&<Modal title="Create New Project" onClose={()=>setMo(false)}><div style={{marginBottom:16}}><label style={{fontSize:13,fontWeight:500,color:"var(--tx2)",display:"block",marginBottom:4}}>Project name *</label><input value={nm} onChange={e=>setNm(e.target.value)} placeholder="e.g. My Store Reviews"/></div><div style={{marginBottom:16}}><label style={{fontSize:13,fontWeight:500,color:"var(--tx2)",display:"block",marginBottom:4}}>Industry</label><select><option>E-commerce</option><option>SaaS</option><option>Restaurant</option><option>Healthcare</option><option>Agency</option></select></div><button className="btn btn-navy" style={{width:"100%"}} onClick={()=>{if(!nm.trim()){show("Name required","error");return}show("Project created!");setMo(false);setNm("");nav("project")}}>Create Project</button></Modal>}
</div>};

/* ═══ PROJECT DETAIL ═══ */
const ProjDet=({nav,show,st})=>{const [tab,setTab]=useState(st||"analysis");const [paste,setPaste]=useState("");const [filt,setFilt]=useState("All");const [loading,setLoading]=useState(false);const [inputMode,setInputMode]=useState("paste");const [csvFile,setCsvFile]=useState(null);
  const analyze=()=>{setLoading(true);setTimeout(()=>{setLoading(false);setTab("analysis");show("Analysis complete!")},2000)};
  const fil=REVIEWS.filter(r=>filt==="All"||r.sent===filt.toLowerCase());
  return <div>
    <div style={{display:"flex",alignItems:"center",gap:8,marginBottom:4,fontSize:13,color:"var(--tx3)"}}><span style={{cursor:"pointer"}} onClick={()=>nav("projects")}>Projects</span><span>/</span><span style={{color:"var(--tx2)"}}>ShopEase Google Reviews</span></div>
    <h1 style={{fontSize:24,fontWeight:600,marginBottom:16}}>ShopEase Google Reviews</h1>
    <div style={{display:"flex",gap:0,borderBottom:"2px solid var(--bd)",marginBottom:24}}>{[["add","Add Reviews","plus"],["analysis","Analysis","bar"],["reviews","Reviews","msg"],["history","History","clk"]].map(([id,l,ic])=><div key={id} onClick={()=>setTab(id)} style={{padding:"10px 20px",fontSize:14,fontWeight:tab===id?600:400,color:tab===id?"var(--navy)":"var(--tx2)",borderBottom:tab===id?"2px solid var(--teal)":"2px solid transparent",cursor:"pointer",display:"flex",alignItems:"center",gap:6,marginBottom:-2}}><I name={ic} size={16} color={tab===id?"var(--teal)":"var(--tx3)"}/>{l}</div>)}</div>

    {tab==="add"&&<div><div style={{display:"flex",gap:0,marginBottom:16}}>{[["paste","Paste Reviews"],["csv","Upload CSV"]].map(([id,l])=><div key={id} onClick={()=>setInputMode(id)} style={{padding:"8px 16px",fontSize:13,fontWeight:inputMode===id?600:400,color:inputMode===id?"var(--teal)":"var(--tx2)",borderBottom:inputMode===id?"2px solid var(--teal)":"2px solid var(--bd)",cursor:"pointer"}}>{l}</div>)}</div>
      {inputMode==="paste"?<div><textarea value={paste} onChange={e=>setPaste(e.target.value)} rows={8} placeholder="Paste reviews here...\n\nSeparate with blank lines." style={{resize:"vertical",lineHeight:1.6}}/><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginTop:12}}><span style={{fontSize:13,color:"var(--tx3)"}}>Detected: {paste.trim()?paste.split(/\n\n+/).filter(Boolean).length:0}</span><div style={{display:"flex",gap:8}}>{paste.trim()&&<button className="btn btn-outline" onClick={()=>{setPaste("");show("Cleared","info")}}>Clear</button>}<button className="btn btn-teal" onClick={()=>{if(!paste.trim()){show("Paste reviews first","error");return}show(`${paste.split(/\n\n+/).filter(Boolean).length} added!`);setPaste("");analyze()}}>Add Reviews</button></div></div></div>
      :<div><div onClick={()=>setCsvFile("customer_reviews.csv")} style={{border:"2px dashed var(--bd2)",borderRadius:12,padding:"48px 24px",textAlign:"center",background:"var(--bg3)",cursor:"pointer"}}>{!csvFile?<><I name="up" size={32} color="var(--tx3)"/><div style={{fontWeight:600,fontSize:14,marginTop:12}}>Drag and drop CSV here</div><div style={{fontSize:13,color:"var(--tx3)",marginTop:4}}>or <span style={{color:"var(--teal)",fontWeight:500}}>browse files</span></div></>:<div><div style={{display:"flex",alignItems:"center",justifyContent:"center",gap:8,marginBottom:8}}><I name="ok" size={20} color="var(--pos)"/><span style={{fontWeight:600}}>{csvFile}</span><span onClick={e=>{e.stopPropagation();setCsvFile(null)}} style={{color:"var(--neg)",cursor:"pointer",fontSize:12,marginLeft:8}}>Remove</span></div><div style={{fontSize:12,color:"var(--tx2)",background:"var(--tealbg)",borderRadius:6,padding:"6px 10px"}}>47 reviews detected, 4 columns mapped</div></div>}</div>{csvFile&&<div style={{display:"flex",justifyContent:"flex-end",marginTop:12}}><button className="btn btn-teal" onClick={()=>{show("47 imported!");setCsvFile(null);analyze()}}>Import 47 Reviews</button></div>}</div>}
    </div>}
    {tab==="analysis"&&(loading?<div style={{textAlign:"center",padding:"80px 0"}}><Spin/><div style={{fontWeight:600,fontSize:16,marginBottom:8}}>Analyzing...</div><div style={{fontSize:14,color:"var(--tx2)"}}>Detecting patterns and generating insights</div></div>:<div>
      <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16,flexWrap:"wrap",gap:8}}><span style={{fontSize:13,color:"var(--tx3)"}}>{ANA.count} reviews · {ANA.date}</span><div style={{display:"flex",gap:8}}><button className="btn btn-outline" style={{display:"flex",alignItems:"center",gap:4}} onClick={()=>show("Downloaded!","info")}><I name="dl" size={14}/>Export</button><button className="btn btn-outline" style={{display:"flex",alignItems:"center",gap:4}} onClick={()=>show("Link copied!","info")}><I name="share" size={14}/>Share</button><button className="btn btn-teal" onClick={analyze}>Re-analyze</button></div></div>
      <AnalysisResults nav={nav} show={show}/>
    </div>)}
    {tab==="reviews"&&<div><div style={{display:"flex",gap:8,marginBottom:16,flexWrap:"wrap"}}><div style={{display:"flex",alignItems:"center",border:"1px solid var(--bd2)",borderRadius:8,padding:"0 10px",flex:1,minWidth:200,background:"var(--bg2)"}}><I name="srch" size={16} color="var(--tx3)"/><input placeholder="Search..." style={{border:"none",padding:8,fontSize:13,flex:1}}/></div>{["All","Positive","Neutral","Negative","Mixed"].map(f=><button key={f} onClick={()=>setFilt(f)} className={`btn ${filt===f?"btn-navy":"btn-outline"}`} style={{padding:"8px 14px",fontSize:13}}>{f}</button>)}</div><div style={{fontSize:13,color:"var(--tx3)",marginBottom:12}}>Showing {fil.length} of {REVIEWS.length}</div>{fil.map(r=><div key={r.id} className="card" style={{borderLeft:`4px solid ${r.sent==="positive"?"var(--pos)":r.sent==="negative"?"var(--neg)":r.sent==="mixed"?"var(--warn)":"var(--tx3)"}`,padding:16,marginBottom:10}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><div style={{display:"flex",gap:8,alignItems:"center"}}><St n={r.rating}/><span style={{fontSize:12,color:"var(--tx3)"}}>{r.author} · {r.date}</span></div><Bg>{r.src}</Bg></div><p style={{fontSize:14,lineHeight:1.6,marginBottom:8}}>{r.text}</p><div style={{display:"flex",gap:6}}>{r.tags.map(t=><Bg key={t}>{t}</Bg>)}</div></div>)}</div>}
    {tab==="history"&&<div>{[{d:"Mar 28, 2026",r:234,s:61,sm:"Shipping top issue."},{d:"Mar 15",r:198,s:58,sm:"Quality complaints rising."},{d:"Mar 1",r:156,s:63,sm:"Stable. Feature requests up."}].map((h,i)=><div key={i} className="card card-click" style={{padding:20,marginBottom:12}} onClick={()=>{setTab("analysis");show("Viewing "+h.d,"info")}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:8}}><span style={{fontWeight:600,fontSize:14}}>{h.d}</span><div style={{display:"flex",gap:8}}><Bg>{h.r} reviews</Bg><Bg c={h.s>=60?"var(--pos)":"var(--warn)"} bg={h.s>=60?"var(--posbg)":"var(--warnbg)"}>Score: {h.s}</Bg></div></div><p style={{fontSize:13,color:"var(--tx2)"}}>{h.sm}</p></div>)}</div>}
  </div>;
};

/* ═══ TRENDS ═══ */
const TrendsP=()=>{const [range,setRange]=useState("6M");const [selT,setSelT]=useState("All");const d=TRENDS;
  const mx=Math.max(...d.map(x=>x.s)),mn=Math.min(...d.map(x=>x.s));
  const pts=d.map((x,i)=>({x:i*(100/(d.length-1)),y:100-((x.s-mn+5)/((mx-mn)+10))*100}));
  const line=pts.map((p,i)=>i===0?`M${p.x},${p.y}`:`L${p.x},${p.y}`).join(" ");
  const topics=[{name:"Shipping",data:[32,28,22,25,20,18],dir:"down",ch:-44},{name:"Quality",data:[70,68,62,58,55,52],dir:"down",ch:-26},{name:"Support",data:[78,80,82,85,88,90],dir:"up",ch:15},{name:"Pricing",data:[45,44,42,43,41,40],dir:"down",ch:-11}];
  const ct=selT!=="All"?topics.find(t=>t.name===selT):null;
  const tPts=ct?ct.data.map((v,i)=>({x:i*(100/(ct.data.length-1)),y:100-(v/100)*100})):[];
  const tLine=tPts.map((p,i)=>i===0?`M${p.x},${p.y}`:`L${p.x},${p.y}`).join(" ");
  return <div>
    <div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:24,flexWrap:"wrap",gap:12}}><h1 style={{fontSize:24,fontWeight:600}}>Trends</h1><div style={{display:"flex",gap:4,background:"var(--bg3)",borderRadius:8,padding:2}}>{["1M","3M","6M","1Y"].map(r=><button key={r} onClick={()=>setRange(r)} className="btn" style={{background:range===r?"var(--bg2)":"transparent",color:range===r?"var(--tx)":"var(--tx2)",padding:"6px 12px",fontSize:13,fontWeight:range===r?600:400,boxShadow:range===r?"0 1px 3px rgba(0,0,0,0.08)":"none"}}>{r}</button>)}</div></div>
    <div className="stat-grid" style={{display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:24}}>{[["Sentiment","61/100","+6","var(--pos)"],["Reviews","234","↑ 18%","var(--pos)"],["Rating","3.4★","stable","var(--warn)"],["Response","89%","↑ 12%","var(--pos)"]].map(([l,v,ch,cc])=><div key={l} className="card" style={{padding:"16px 20px"}}><div style={{fontSize:12,color:"var(--tx2)",textTransform:"uppercase",letterSpacing:"0.05em",fontWeight:500,marginBottom:4}}>{l}</div><div style={{fontSize:24,fontWeight:600}}>{v}</div><div style={{fontSize:12,color:cc,fontWeight:500}}>{ch}</div></div>)}</div>
    <div className="card" style={{padding:24,marginBottom:24}}><div style={{fontWeight:600,fontSize:16,marginBottom:16}}>Sentiment Over Time</div><div style={{height:140,marginBottom:8}}><svg viewBox="0 0 100 100" preserveAspectRatio="none" style={{width:"100%",height:"100%"}}><defs><linearGradient id="ag" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0D9488" stopOpacity="0.2"/><stop offset="100%" stopColor="#0D9488" stopOpacity="0.02"/></linearGradient></defs>{[20,40,60,80].map(y=><line key={y} x1="0" y1={y} x2="100" y2={y} stroke="var(--bd)" strokeWidth="0.3"/>)}<path d={line+` L100,100 L0,100 Z`} fill="url(#ag)"/><path d={line} fill="none" stroke="var(--teal)" strokeWidth="1.5" strokeLinejoin="round" strokeLinecap="round"/>{pts.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="2.5" fill="var(--bg2)" stroke="var(--teal)" strokeWidth="1.5"/>)}</svg></div><div style={{display:"flex",justifyContent:"space-between"}}>{d.map(x=><div key={x.m} style={{textAlign:"center"}}><div style={{fontSize:16,fontWeight:600}}>{x.s}</div><div style={{fontSize:11,color:"var(--tx3)"}}>{x.m}</div></div>)}</div></div>
    <div className="card" style={{padding:24,marginBottom:24}}><div style={{fontWeight:600,fontSize:16,marginBottom:12}}>Sentiment Breakdown</div><div style={{display:"flex",gap:16,fontSize:12,marginBottom:12}}>{[["Positive","var(--pos)"],["Neutral","var(--tx3)"],["Negative","var(--neg)"]].map(([l,c])=><span key={l} style={{display:"flex",alignItems:"center",gap:4}}><span style={{width:10,height:10,borderRadius:2,background:c}}/>{l}</span>)}</div>{d.map(x=><div key={x.m} style={{display:"flex",alignItems:"center",gap:12,marginBottom:8}}><span style={{width:28,fontSize:12,color:"var(--tx2)",fontWeight:500}}>{x.m}</span><div style={{flex:1,display:"flex",borderRadius:4,overflow:"hidden",height:24}}><div style={{width:`${x.pos}%`,background:"var(--pos)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,color:"#fff",fontWeight:600}}>{x.pos}%</div><div style={{width:`${x.neu}%`,background:"#94A3B8",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,color:"#fff"}}>{x.neu}%</div><div style={{width:`${x.neg}%`,background:"var(--neg)",display:"flex",alignItems:"center",justifyContent:"center",fontSize:10,color:"#fff"}}>{x.neg}%</div></div></div>)}</div>
    <div className="card" style={{padding:24,marginBottom:24}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",marginBottom:16}}><div style={{fontWeight:600,fontSize:16}}>Topic Tracking</div><select value={selT} onChange={e=>setSelT(e.target.value)} style={{width:"auto"}}><option>All</option>{topics.map(t=><option key={t.name}>{t.name}</option>)}</select></div>
      {selT==="All"?<div className="grid-2" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:12}}>{topics.map(t=><div key={t.name} className="card card-click" style={{padding:16}} onClick={()=>setSelT(t.name)}><div style={{display:"flex",justifyContent:"space-between",marginBottom:8}}><span style={{fontWeight:600,fontSize:14}}>{t.name}</span><span style={{fontSize:12,fontWeight:600,color:t.dir==="up"?"var(--pos)":"var(--neg)"}}>{t.ch>0?"+":""}{t.ch}%</span></div><div style={{display:"flex",alignItems:"flex-end",gap:3,height:32}}>{t.data.map((v,i)=><div key={i} style={{flex:1,background:t.dir==="up"?"var(--posbg)":"var(--negbg)",borderRadius:"2px 2px 0 0",height:`${(v/100)*32}px`}}/>)}</div></div>)}</div>
      :<div><div style={{display:"flex",alignItems:"center",gap:12,marginBottom:16}}><span style={{fontWeight:600}}>{ct.name}</span><Bg c={ct.dir==="up"?"var(--pos)":"var(--neg)"} bg={ct.dir==="up"?"var(--posbg)":"var(--negbg)"}>{ct.ch>0?"+":""}{ct.ch}%</Bg><button className="btn btn-outline" style={{marginLeft:"auto",padding:"4px 12px",fontSize:12}} onClick={()=>setSelT("All")}>All topics</button></div><div style={{height:100,marginBottom:8}}><svg viewBox="0 0 100 100" preserveAspectRatio="none" style={{width:"100%",height:"100%"}}>{[25,50,75].map(y=><line key={y} x1="0" y1={y} x2="100" y2={y} stroke="var(--bd)" strokeWidth="0.3"/>)}<path d={tLine} fill="none" stroke={ct.dir==="up"?"var(--pos)":"var(--neg)"} strokeWidth="1.5" strokeLinejoin="round" strokeLinecap="round"/>{tPts.map((p,i)=><circle key={i} cx={p.x} cy={p.y} r="2.5" fill="var(--bg2)" stroke={ct.dir==="up"?"var(--pos)":"var(--neg)"} strokeWidth="1.5"/>)}</svg></div><div style={{display:"flex",justifyContent:"space-between"}}>{ct.data.map((v,i)=><div key={i} style={{textAlign:"center"}}><div style={{fontSize:14,fontWeight:600}}>{v}%</div><div style={{fontSize:11,color:"var(--tx3)"}}>{d[i].m}</div></div>)}</div></div>}
    </div>
    <div className="card" style={{padding:24,marginBottom:24}}><div style={{fontWeight:600,fontSize:16,marginBottom:12}}>Industry Benchmarks</div>{[["Sentiment","61","68","ahead"],["Response","89%","72%","ahead"],["Rating","3.4★","3.8★","below"],["Resolution","4.2h","8.1h","ahead"]].map(([l,y,av,s],i)=><div key={i} style={{display:"flex",alignItems:"center",gap:16,padding:"12px 0",borderBottom:i<3?"1px solid var(--bd)":"none"}}><span style={{flex:1,fontSize:14,fontWeight:500}}>{l}</span><div style={{textAlign:"right",width:60}}><div style={{fontSize:14,fontWeight:600,color:"var(--teal)"}}>{y}</div><div style={{fontSize:11,color:"var(--tx3)"}}>You</div></div><div style={{textAlign:"right",width:60}}><div style={{fontSize:14,fontWeight:600,color:"var(--tx2)"}}>{av}</div><div style={{fontSize:11,color:"var(--tx3)"}}>Avg</div></div><Bg c={s==="ahead"?"var(--pos)":"var(--neg)"} bg={s==="ahead"?"var(--posbg)":"var(--negbg)"}>{s==="ahead"?"Ahead":"Below"}</Bg></div>)}</div>
    <div className="grid-2" style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:16}}>
      <div className="card" style={{padding:20}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><I name="warn" size={18} color="var(--neg)"/><span style={{fontWeight:600,fontSize:15}}>Emerging Issues</span></div>{[{t:"'App crashes' up 45%",d:"+45%",s:"critical"},{t:"'Wrong item' new",d:"NEW",s:"high"}].map((a,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 0",borderBottom:i<1?"1px solid var(--bd)":"none"}}><Bg c={SC[a.s].c} bg={SC[a.s].bg}>{a.d}</Bg><span style={{fontSize:13}}>{a.t}</span></div>)}</div>
      <div className="card" style={{padding:20}}><div style={{display:"flex",alignItems:"center",gap:8,marginBottom:12}}><I name="trend" size={18} color="var(--pos)"/><span style={{fontWeight:600,fontSize:15}}>Improving</span></div>{[{t:"Onboarding praise up 20%",d:"+20%"},{t:"Support time improving",d:"+15%"}].map((a,i)=><div key={i} style={{display:"flex",alignItems:"center",gap:10,padding:"10px 0",borderBottom:i<1?"1px solid var(--bd)":"none"}}><Bg c="var(--pos)" bg="var(--posbg)">{a.d}</Bg><span style={{fontSize:13}}>{a.t}</span></div>)}</div>
    </div>
  </div>;
};

/* ═══ INTEGRATIONS ═══ */
const IntegP=({show})=>{const [conn,setConn]=useState({"Google Business":true,"Yelp":true});const tog=n=>{setConn(p=>{const x={...p};if(x[n])delete x[n];else x[n]=true;return x});show(conn[n]?`${n} disconnected`:`${n} connected!`)};
  return <div><h1 style={{fontSize:24,fontWeight:600,marginBottom:24}}>Integrations</h1><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fill,minmax(240px,1fr))",gap:12}}>{["Google Business","Yelp","Trustpilot","G2","Capterra","Amazon","App Store","Slack","Zapier"].map(n=><div key={n} className="card" style={{padding:20,textAlign:"center"}}><div style={{width:40,height:40,borderRadius:10,background:conn[n]?"var(--posbg)":"var(--bg3)",margin:"0 auto 12px",display:"flex",alignItems:"center",justifyContent:"center"}}>{conn[n]?<I name="ok" size={20} color="var(--pos)"/>:<span style={{fontSize:18,fontWeight:700,color:"var(--tx2)"}}>{n[0]}</span>}</div><div style={{fontWeight:600,fontSize:14,marginBottom:4}}>{n}</div><div style={{fontSize:12,color:"var(--tx3)",marginBottom:12}}>{conn[n]?"Connected":"Not connected"}</div><button className={`btn ${conn[n]?"btn-outline":"btn-navy"}`} style={{fontSize:13}} onClick={()=>tog(n)}>{conn[n]?"Disconnect":"Connect"}</button></div>)}</div></div>;
};

/* ═══ SETTINGS ═══ */
const SetP=({nav,show})=>{const [del,setDel]=useState(false);const [notifs,setNotifs]=useState({weekly:true,critical:true,monthly:false});const togN=k=>setNotifs(p=>({...p,[k]:!p[k]}));
  return <div><h1 style={{fontSize:24,fontWeight:600,marginBottom:24}}>Settings</h1>
    <div className="card" style={{padding:24,maxWidth:600,marginBottom:16}}><div style={{fontWeight:600,fontSize:16,marginBottom:20}}>Profile</div>{[["Full name","Sthe Mahlangu",false],["Email","sthe@reviewpulse.com",true],["Company","",false]].map(([l,v,ro])=><div key={l} style={{marginBottom:16}}><label style={{fontSize:13,fontWeight:500,color:"var(--tx2)",display:"block",marginBottom:4}}>{l}</label><input defaultValue={v} readOnly={ro} style={{background:ro?"var(--bg3)":"var(--bg2)"}}/></div>)}<button className="btn btn-navy" onClick={()=>show("Saved!")}>Save Changes</button></div>
    <div className="card" style={{padding:24,maxWidth:600,marginBottom:16}}><div style={{fontWeight:600,fontSize:16,marginBottom:16}}>Notifications</div>{[["weekly","Weekly digest","Summary every Monday"],["critical","Critical alerts","Instant email on issues"],["monthly","Monthly report","Usage & billing"]].map(([k,t,d])=><div key={k} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"12px 0",borderBottom:"1px solid var(--bd)"}}><div><div style={{fontSize:14,fontWeight:500}}>{t}</div><div style={{fontSize:12,color:"var(--tx3)"}}>{d}</div></div><div onClick={()=>{togN(k);show(notifs[k]?"Off":"On","info")}} style={{width:44,height:24,borderRadius:12,background:notifs[k]?"var(--teal)":"var(--bd2)",cursor:"pointer",position:"relative",transition:"background 0.2s"}}><div style={{width:20,height:20,borderRadius:"50%",background:"#fff",position:"absolute",top:2,left:notifs[k]?22:2,transition:"left 0.2s",boxShadow:"0 1px 3px rgba(0,0,0,0.15)"}}/></div></div>)}</div>
    <div className="card" style={{padding:24,maxWidth:600,borderColor:"var(--neg)"}}><div style={{fontWeight:600,fontSize:14,color:"var(--neg)",marginBottom:8}}>Danger Zone</div><button className="btn" style={{background:"var(--bg2)",color:"var(--neg)",border:"1px solid var(--neg)",padding:"8px 16px",fontSize:13}} onClick={()=>setDel(true)}>Delete Account</button></div>
    {del&&<Modal title="Delete Account" onClose={()=>setDel(false)}><p style={{fontSize:14,color:"var(--tx2)",lineHeight:1.6,marginBottom:20}}>Permanently deletes everything. Cannot be undone.</p><div style={{display:"flex",gap:8}}><button className="btn btn-outline" style={{flex:1}} onClick={()=>setDel(false)}>Cancel</button><button className="btn" style={{flex:1,background:"var(--neg)",color:"#fff"}} onClick={()=>{setDel(false);nav("landing")}}>Delete</button></div></Modal>}
  </div>;
};

/* ═══ BILLING ═══ */
const BillP=({nav,show})=>{const [pm,setPm]=useState(false);return <div><h1 style={{fontSize:24,fontWeight:600,marginBottom:24}}>Billing</h1><div style={{display:"grid",gap:16,maxWidth:700}}>
  <div className="card" style={{padding:24}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div style={{fontWeight:600,fontSize:16}}>Pro Plan</div><div style={{fontSize:14,color:"var(--tx2)"}}>$29/mo · Renews Apr 1</div></div><button className="btn btn-outline" onClick={()=>setPm(true)}>Change Plan</button></div></div>
  <div className="card" style={{padding:24}}><div style={{fontWeight:600,fontSize:16,marginBottom:16}}>Usage</div>{[["Reviews",127,500],["Analyses",13,999],["Projects",3,10]].map(([l,u,t])=><div key={l} style={{marginBottom:12}}><div style={{display:"flex",justifyContent:"space-between",fontSize:13,marginBottom:4}}><span style={{color:"var(--tx2)"}}>{l}</span><span style={{fontWeight:600}}>{u}/{t===999?"∞":t}</span></div><div style={{height:6,background:"var(--bd)",borderRadius:3}}><div style={{height:"100%",background:"var(--teal)",borderRadius:3,width:`${Math.min((u/t)*100,100)}%`}}/></div></div>)}</div>
  <div className="card" style={{padding:24}}><div style={{fontWeight:600,fontSize:16,marginBottom:4}}>Payment</div><div style={{fontSize:14,color:"var(--tx2)",marginBottom:12}}>Visa ending 4242</div><button className="btn btn-outline" onClick={()=>show("Redirecting...","info")}>Update</button></div>
  <div className="card" style={{padding:24}}><div style={{fontWeight:600,fontSize:16,marginBottom:12}}>History</div><table style={{width:"100%",fontSize:13,borderCollapse:"collapse"}}><tbody>{INVOICES.map((inv,i)=><tr key={i} style={{borderBottom:"1px solid var(--bd)"}}><td style={{padding:"10px 0",color:"var(--tx2)"}}>{inv.d}</td><td>{inv.desc}</td><td style={{fontWeight:600}}>{inv.amt}</td><td><span onClick={()=>show("Downloaded!","info")} style={{color:"var(--navy)",cursor:"pointer",fontSize:12}}>PDF ↓</span></td></tr>)}</tbody></table></div>
</div>
  {pm&&<Modal title="Change Plan" onClose={()=>setPm(false)}>{[["Free","$0/mo","50 reviews"],["Pro","$29/mo","500 reviews"],["Business","$79/mo","Unlimited"]].map(([n,p,d])=><div key={n} style={{display:"flex",justifyContent:"space-between",alignItems:"center",padding:"16px 0",borderBottom:"1px solid var(--bd)"}}><div><div style={{fontWeight:600}}>{n} <span style={{fontWeight:400,color:"var(--tx2)"}}>{p}</span></div><div style={{fontSize:13,color:"var(--tx3)"}}>{d}</div></div>{n==="Pro"?<Bg c="var(--pos)" bg="var(--posbg)">Current</Bg>:<button className="btn btn-navy" style={{fontSize:13}} onClick={()=>{show(`Switched to ${n}!`);setPm(false)}}>Switch</button>}</div>)}</Modal>}
</div>};

/* ═══ APP ═══ */
export default function App(){
  const [page,setPage]=useState("landing");
  const [dark,setDark]=useState(false);
  const nav=p=>{setPage(p);window.scrollTo(0,0)};
  const tog=()=>setDark(d=>!d);
  const w=ch=><div className={dark?"dark":""}>{ch}</div>;
  if(page==="landing")return w(<Landing nav={nav} dark={dark} tog={tog}/>);
  if(["login","signup","forgot"].includes(page))return w(<Auth type={page} nav={nav}/>);
  return w(<Shell page={page} nav={nav} dark={dark} tog={tog}/>);
}
